# Generated by Django 4.1.1 on 2024-09-15 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TVDisplayResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TVDisplayTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TVOperationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(max_length=50)),
                ('tv_released_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2024)])),
                ('tv_screen_size', models.IntegerField()),
                ('smart_tv', models.BooleanField(default=True)),
                ('refresh_rate', models.IntegerField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.brand')),
                ('display_resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.tvdisplayresolution')),
                ('display_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.tvdisplaytechnology')),
                ('operation_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.tvoperationsystem')),
            ],
        ),
    ]
