# Generated by Django 4.1.1 on 2024-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_television_image_television_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='televisions', to='viewer.category'),
        ),
    ]
