# Generated by Django 4.1.1 on 2024-10-12 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_remove_profile_biography_profile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='communication_channel',
            field=models.CharField(choices=[('POST', 'Pošta'), ('EMAIL', 'Email'), ('TELEPHONE', 'Telefon')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Nesprávný formát čísla.', regex='^\\+?\\d+$'), django.core.validators.MinLengthValidator(9, message='Telefonní číslo musí mít alespoň 9 znaků.')]),
        ),
    ]
