# Generated by Django 4.1.1 on 2024-10-18 18:49

import django.core.validators
from django.db import migrations, models
import viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_order_price_itemsonstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsonstock',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Povoleny jsou pouze znaky a-z nebo A-Z.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[viewer.models.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Povoleny jsou pouze znaky a-z nebo A-Z.', regex='^[a-zA-Z]+$'), django.core.validators.MinLengthValidator(2, message='Jméno musí mít alespoň 2 znaky.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Povoleny jsou pouze znaky a-z nebo A-Z.', regex='^[a-zA-Z]+$'), django.core.validators.MinLengthValidator(2, message='Příjmení musí mít alespoň 2 znaky.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Nesprávný formát čísla. Povolené jsou pouze číslice a volitelně "+" na začátku.', regex='^\\+?\\d{9,}$')]),
        ),
        migrations.AddConstraint(
            model_name='itemsonstock',
            constraint=models.UniqueConstraint(fields=('television_id',), name='unique_television'),
        ),
    ]
